name: Publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials for AWS CodeArtifact
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_KEY }}
          # Note: CodeArtifact is in us-west-2, NOT us-west-1
          aws-region: us-west-2
          mask-aws-account-id: false
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-codeartifact-write-role
          role-skip-session-tagging: true
          role-duration-seconds: 1200
      
      - name: Setup Python for Python projects
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Build
        run: |-
          poetry build
      
      - name: Publish
        run: |-
          repo_url="$(aws codeartifact get-repository-endpoint --domain-owner ${AWS_ACCOUNT_ID} --domain "${AWS_CODEARTIFACT_REPO_DOMAIN}" --repository "${AWS_CODEARTIFACT_REPO_NAME}" --format pypi --query 'repositoryEndpoint' --output text)"
          repo_password="$(aws codeartifact get-authorization-token --domain-owner ${AWS_ACCOUNT_ID} --domain ${AWS_CODEARTIFACT_REPO_DOMAIN} --query 'authorizationToken' --output text)"

          poetry config repositories.verses-internal "${repo_url}"
          poetry publish --repository verses-internal --username aws --password "${repo_password}"
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_CODEARTIFACT_REPO_DOMAIN: versestech
          AWS_CODEARTIFACT_REPO_NAME: pypi-internal
